### PR TITLE
simplify Dockerfile to use standard tf 2.0 image

### LINKED ISSUE #64: Upgrade Dockerfile to Tensorflow 2.0
Need help to upgrade Dockerfile to Tensorflow 2.0

### PR DESCRIPTION
**Pull request by chanwit**
This PR simplifies the `Dockerfile` using the standard tensorflow 2.0 image.

Fixes #64

### CODE REVIEW

**Comment by chanwit** [comment]
ping @kittinan @titipata 

could you please build it with `docker build -t deepcut:dev .`
then `docker run -it deepcut:dev` to check if the deepcut working for you?

**Comment by kittinan** [comment]
work for me :tada:  :thailand: 

Screenshot-root@5f899ebbb066: -

**Comment by titipata** [comment]
Do we have to fix the README too? But looks great!

**Review by titipata — APPROVED** [review]
LGTM!

**Comment by titipata** [comment]
I updated the `README` according to the PR. It works for me perfectly. Thanks @chanwit, @kittinan!

**Pull request merged**
